project:
  type: website
  output-dir: docs

website:
  title: "Minzc"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/zicun-cong-390086a4/
      - icon: github
        text: Github
        href: https://github.com/Minzc
format:
  html:
    theme: cosmo
    css: styles.css



