project:
  type: website
  output-dir: docs

website:
  title: "Zicun Cong's Homepage"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/zicun-cong-390086a4/
      - icon: github
        text: Github
        href: https://github.com/Minzc
  page-footer: 
    background: light
    center: 
      - "Last Update Aug. 2022"

format:
  html:
    page-layout: full
    theme: cosmo   
    # theme: 
      # - green_theme.scss
    css: styles.css
    toc: true
    # mainfont: Nunito



